#created on: Jul 30, 2010
package edu.isi.bmkeg.pdf.classification.rules

#list any import classes here.

import edu.isi.bmkeg.pdf.features.ChunkFeatures;
import edu.isi.bmkeg.pdf.model.ChunkBlock;

#declare any global variables here

global ChunkBlock    chunk;


rule "Title"
no-loop
	activation-group "blockClassification"
	salience 4
	when
		    ChunkFeatures(pageNumber==1)
		    ChunkFeatures(heightDifferenceBetweenChunkWordAndDocumentWord>2)
		  
		    eval(chunk.getNumberOfLine()<=6)
		    ChunkFeatures(allignedMiddle==true)
		    ChunkFeatures(mostPopularFontModifierBold==true)
	then 
		chunk.setType(chunk.TYPE_TITLE);
		
end

rule "allnames"
no-loop
	activation-group "blockClassification"
	salience 4
	when
		    ChunkFeatures(allNames==true)
	then 
		chunk.setType(chunk.ALLNAMES);
		
end


rule "Header"
no-loop
activation-group "blockClassification"
salience 4
	when
		 eval(chunk.getNumberOfLine()==1)
		    ChunkFeatures(mostPopularFontModifierBold==true)
	then
		 chunk.setType(chunk.TYPE_HEADER);
end
